Repository aws-controllers-k8s/acm-controller, pull requests merged in 2023-01, with the labels that each got.

#2 Adds support for Certificate resources
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/certificate.go
  apis/v1alpha1/enums.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  cmd/controller/main.go
  config/crd/bases/acm.services.k8s.aws_certificates.yaml
  config/crd/kustomization.yaml
  config/rbac/cluster-role-controller.yaml
  config/rbac/role-reader.yaml
  config/rbac/role-writer.yaml
  generator.yaml
  helm/crds/acm.services.k8s.aws_certificates.yaml
  helm/templates/cluster-role-controller.yaml
  helm/templates/deployment.yaml
  helm/templates/role-reader.yaml
  helm/templates/role-writer.yaml
  helm/values.schema.json
  helm/values.yaml
  pkg/resource/certificate/delta.go
  pkg/resource/certificate/descriptor.go
  pkg/resource/certificate/hooks.go
  pkg/resource/certificate/identifiers.go
  pkg/resource/certificate/manager.go
  pkg/resource/certificate/manager_factory.go
  pkg/resource/certificate/references.go
  pkg/resource/certificate/resource.go
  pkg/resource/certificate/sdk.go
  pkg/resource/certificate/tags.go
  templates/hooks/certificate/sdk_create_post_set_output.go.tpl
  templates/hooks/certificate/sdk_create_pre_build_request.go.tpl
Labels: lgtm, approved

#4 Add metadata
  metadata.yaml
Labels: approved

#3 Adds basic e2e test for certificate
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/certificate.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/acm.services.k8s.aws_certificates.yaml
  config/iam/recommended-inline-policy
  generator.yaml
  helm/crds/acm.services.k8s.aws_certificates.yaml
  pkg/resource/certificate/delta.go
  pkg/resource/certificate/manager.go
  pkg/resource/certificate/manager_factory.go
  pkg/resource/certificate/sdk.go
  templates/hooks/certificate/sdk_create_post_set_output.go.tpl
  test/e2e/__init__.py
  test/e2e/certificate.py
  test/e2e/condition.py
  test/e2e/resources/certificate_public.yaml
  test/e2e/tests/test_certificate.py
Labels: lgtm, approved

#5 updating the olm config with proper branding and custom resource info
  olm/olmconfig.yaml
Labels: lgtm, approved, needs-ok-to-test
