Repository aws-controllers-k8s/acm-controller, pull requests merged in 2024-02, with the labels that each got.

#29 Add a `DomainValidations` field in `Certificate` status
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/certificate.go
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/acm.services.k8s.aws_certificates.yaml
  generator.yaml
  helm/crds/acm.services.k8s.aws_certificates.yaml
  pkg/resource/certificate/sdk.go
  templates/hooks/certificate/sdk_read_one_pre_set_output.go.tpl
Labels: lgtm, approved, ok-to-test

#30 Release artifacts for release `v0.0.12`
  apis/v1alpha1/ack-generate-metadata.yaml
  config/controller/kustomization.yaml
  config/crd/bases/acm.services.k8s.aws_certificates.yaml
  helm/Chart.yaml
  helm/crds/acm.services.k8s.aws_certificates.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: lgtm, approved, needs-ok-to-test

#32 Support tag updates for `Certificate` resource
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/certificate/hooks.go
  pkg/resource/certificate/sdk.go
  pkg/tags/sync.go
  templates/hooks/certificate/sdk_read_one_pre_set_output.go.tpl
  templates/hooks/certificate/sdk_update_pre_build_request.go.tpl
  test/e2e/certificate.py
  test/e2e/resources/certificate_public.yaml
  test/e2e/tests/test_certificate.py
Labels: lgtm, approved
